#!/bin/bash

# Deploy Blue
echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml
kubectl rollout status deployment/django-app-blue

# Deploy Green
echo "Deploying green version..."
kubectl apply -f green_deployment.yaml
kubectl rollout status deployment/django-app-green

# Check logs of green pods
GREEN_POD=$(kubectl get pods -l app=django-app,version=green -o jsonpath="{.items[0].metadata.name}")
echo "Logs from green pod $GREEN_POD:"
kubectl logs $GREEN_POD

# Switch traffic to green
echo "Switching Service to green version..."
kubectl apply -f kubeservice.yaml
