pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/VinnyMelato/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                pip install -r messaging_app/requirements.txt
                pip install pytest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                pytest
                '''
            }
        }
    }
}
